config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/demichie/elicipy:
      branch: main
      repo: https://github.com/demichie/elicipy
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/demichie/elicipy git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-jade-heron.sh
        container: qc.acc_skanky-peach-chimpanzee
  QC.Doc:
    repos:
      github.com/demichie/elicipy find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-puce-quoll.sh
        container: qc.doc_scummy-amber-spitz
      github.com/demichie/elicipy git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-pumpkin-barnacle.sh
        container: qc.doc_flimsy-amaranth-sheepdog
      github.com/demichie/elicipy markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-heliotrope-hound.sh
        container: qc.doc_sleazy-coral-grouse
  QC.Lic:
    repos:
      github.com/demichie/elicipy licensee:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-linen-armadillo.sh
        container: qc.lic_cloudy-cinnabar-deer
  QC.Met:
    repos:
      github.com/demichie/elicipy cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-malachite-shrimp.sh
        container: qc.met_bluesy-beige-deer
  QC.Sec:
    repos:
      github.com/demichie/elicipy bandit:
        commands:
        - /usr/bin/env sh .sqa/script.beady-mustard-otter.sh
        container: qc.sec_tacky-mauve-dane
  QC.Sty:
    repos:
      github.com/demichie/elicipy flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-goldenrod-ocelot.sh
        container: qc.sty_lovely-violet-jackal
  QC.Ver:
    repos:
      github.com/demichie/elicipy get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-white-monster.sh
        container: qc.ver_skinny-eggplant-cichlid
timeout: 5400
