config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/demichie/elicipy:
      branch: main
      repo: https://github.com/demichie/elicipy
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/demichie/elicipy git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-apricot-bat.sh
        container: qc.acc_stealthy-vermilion-rottweiler
  QC.Doc:
    repos:
      github.com/demichie/elicipy find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-cerise-pig.sh
        container: qc.doc_thirsty-emerald-grouse
      github.com/demichie/elicipy git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-aquamarine-orangutan.sh
        container: qc.doc_trippy-tomato-goat
      github.com/demichie/elicipy markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-asparagus-magpie.sh
        container: qc.doc_droopy-ochre-spaniel
  QC.Lic:
    repos:
      github.com/demichie/elicipy licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-saffron-cougar.sh
        container: qc.lic_sunny-periwinkle-mist
  QC.Sec:
    repos:
      github.com/demichie/elicipy bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-puce-vole.sh
        container: qc.sec_dorky-wisteria-hummingbird
  QC.Sty:
    repos:
      github.com/demichie/elicipy flake8:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-denim-spider.sh
        container: qc.sty_cheeky-smalt-hare
  QC.Ver:
    repos:
      github.com/demichie/elicipy get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-wheat-budgerigar.sh
        container: qc.ver_gummy-goldenrod-gerbil
timeout: 5400
