config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/demichie/elicipy:
      branch: main
      repo: https://github.com/demichie/elicipy
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/demichie/elicipy git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-apricot-boar.sh
        container: qc.acc_greasy-sepia-bison
  QC.Doc:
    repos:
      github.com/demichie/elicipy find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-mustard-caterpillar.sh
        container: qc.doc_jumpy-chartreuse-bloodhound
      github.com/demichie/elicipy git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-violet-jellyfish.sh
        container: qc.doc_homey-lemon-collie
      github.com/demichie/elicipy markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-taupe-bloodhound.sh
        container: qc.doc_pasty-orchid-ibis
  QC.Lic:
    repos:
      github.com/demichie/elicipy licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-firebrick-foxhound.sh
        container: qc.lic_smelly-xanthic-caterpillar
  QC.Sec:
    repos:
      github.com/demichie/elicipy bandit:
        commands:
        - /usr/bin/env sh .sqa/script.surly-pink-dhole.sh
        container: qc.sec_shaggy-sangria-chow
  QC.Sty:
    repos:
      github.com/demichie/elicipy flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homely-malachite-macaque.sh
        container: qc.sty_homey-apricot-tamarin
  QC.Ver:
    repos:
      github.com/demichie/elicipy get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-charcoal-fousek.sh
        container: qc.ver_frumpy-ecru-beaver
timeout: 5400
