config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/demichie/elicipy:
      branch: main
      repo: https://github.com/demichie/elicipy
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/demichie/elicipy git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-russet-macaque.sh
        container: qc.acc_woolly-smalt-barnacle
  QC.Doc:
    repos:
      github.com/demichie/elicipy find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-orchid-hippopotamus.sh
        container: qc.doc_foggy-saffron-nightingale
      github.com/demichie/elicipy git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-razzmatazz-seahorse.sh
        container: qc.doc_zippy-asparagus-buffalo
      github.com/demichie/elicipy markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-tangerine-dhole.sh
        container: qc.doc_tacky-white-termite
  QC.Lic:
    repos:
      github.com/demichie/elicipy licensee:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-sangria-sparrow.sh
        container: qc.lic_shabby-pink-tarsier
  QC.Sec:
    repos:
      github.com/demichie/elicipy bandit:
        commands:
        - /usr/bin/env sh .sqa/script.surly-tan-earwig.sh
        container: qc.sec_hilly-aquamarine-kangaroo
  QC.Sty:
    repos:
      github.com/demichie/elicipy flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-puce-newfoundland.sh
        container: qc.sty_slaphappy-seashell-coral
  QC.Ver:
    repos:
      github.com/demichie/elicipy get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-chartreuse-bongo.sh
        container: qc.ver_flabby-cinnabar-budgerigar
timeout: 5400
