config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/demichie/elicipy:
      branch: main
      repo: https://github.com/demichie/elicipy
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/demichie/elicipy git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-persimmon-mist.sh
        container: qc.acc_nerdy-alizarin-indri
  QC.Doc:
    repos:
      github.com/demichie/elicipy find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-crimson-spoonbill.sh
        container: qc.doc_paltry-orange-shrimp
      github.com/demichie/elicipy git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-asparagus-sheep.sh
        container: qc.doc_ready-violet-dormouse
      github.com/demichie/elicipy markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-denim-harrier.sh
        container: qc.doc_slaphappy-cerise-horse
  QC.Lic:
    repos:
      github.com/demichie/elicipy licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-cerise-alligator.sh
        container: qc.lic_droopy-beige-buzzard
  QC.Sec:
    repos:
      github.com/demichie/elicipy bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-crimson-barb.sh
        container: qc.sec_cranky-turquoise-dalmatian
  QC.Sty:
    repos:
      github.com/demichie/elicipy flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-firebrick-hyrax.sh
        container: qc.sty_nippy-champagne-alligator
  QC.Ver:
    repos:
      github.com/demichie/elicipy get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-heliotrope-setter.sh
        container: qc.ver_shaky-rose-tarsier
timeout: 5400
