config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/demichie/elicipy:
      branch: main
      repo: https://github.com/demichie/elicipy
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/demichie/elicipy git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-lemon-sheep.sh
        container: qc.acc_cozy-brass-devil
  QC.Doc:
    repos:
      github.com/demichie/elicipy find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-persimmon-worm.sh
        container: qc.doc_scanty-cinnamon-avocet
      github.com/demichie/elicipy git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-peach-skunk.sh
        container: qc.doc_beady-rose-urchin
      github.com/demichie/elicipy markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-burgundy-fousek.sh
        container: qc.doc_homey-cerise-reindeer
  QC.Lic:
    repos:
      github.com/demichie/elicipy licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-puce-gecko.sh
        container: qc.lic_breezy-denim-emu
  QC.Sec:
    repos:
      github.com/demichie/elicipy bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-sapphire-greyhound.sh
        container: qc.sec_muggy-fuchsia-mongrel
  QC.Sty:
    repos:
      github.com/demichie/elicipy flake8:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-cerulean-wolfhound.sh
        container: qc.sty_droopy-beige-yak
  QC.Ver:
    repos:
      github.com/demichie/elicipy get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-periwinkle-setter.sh
        container: qc.ver_fuzzy-amaranth-lemur
timeout: 5400
