config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/demichie/elicipy:
      branch: main
      repo: https://github.com/demichie/elicipy
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/demichie/elicipy git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-maroon-jaguar.sh
        container: qc.acc_surly-blue-rat
  QC.Doc:
    repos:
      github.com/demichie/elicipy find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-tangerine-civet.sh
        container: qc.doc_leaky-brass-dingo
      github.com/demichie/elicipy git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-maroon-lobster.sh
        container: qc.doc_gimpy-orange-corgi
      github.com/demichie/elicipy markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-green-bobcat.sh
        container: qc.doc_jumpy-viridian-turtle
  QC.Lic:
    repos:
      github.com/demichie/elicipy licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-corn-uakari.sh
        container: qc.lic_goopy-olivine-dolphin
  QC.Sec:
    repos:
      github.com/demichie/elicipy bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-platinum-newt.sh
        container: qc.sec_hazy-coral-rottweiler
  QC.Sty:
    repos:
      github.com/demichie/elicipy flake8:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-blue-kudu.sh
        container: qc.sty_smelly-magnolia-elephant
  QC.Ver:
    repos:
      github.com/demichie/elicipy get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-lemon-oriole.sh
        container: qc.ver_whiny-sangria-monkey
timeout: 5400
