config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/demichie/elicipy:
      branch: main
      repo: https://github.com/demichie/elicipy
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/demichie/elicipy git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-sapphire-tarantula.sh
        container: qc.acc_stinky-flax-harrier
  QC.Doc:
    repos:
      github.com/demichie/elicipy find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-ultramarine-iguana.sh
        container: qc.doc_lovely-lemon-lionfish
      github.com/demichie/elicipy git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-burgundy-argentino.sh
        container: qc.doc_wheezy-olivine-guppy
      github.com/demichie/elicipy markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-black-gecko.sh
        container: qc.doc_nerdy-gold-dragon
  QC.Lic:
    repos:
      github.com/demichie/elicipy licensee:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-wheat-manatee.sh
        container: qc.lic_shaggy-mustard-caracal
  QC.Sec:
    repos:
      github.com/demichie/elicipy bandit:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-cornflower-hound.sh
        container: qc.sec_gimpy-wisteria-sparrow
  QC.Sty:
    repos:
      github.com/demichie/elicipy flake8:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-periwinkle-capuchin.sh
        container: qc.sty_trippy-vermilion-turkey
  QC.Ver:
    repos:
      github.com/demichie/elicipy get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-carmine-wrasse.sh
        container: qc.ver_ready-silver-angelfish
timeout: 5400
