config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/demichie/elicipy:
      branch: main
      repo: https://github.com/demichie/elicipy
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/demichie/elicipy git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-ivory-woodlouse.sh
        container: qc.acc_cozy-cerise-skunk
  QC.Doc:
    repos:
      github.com/demichie/elicipy find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-linen-rat.sh
        container: qc.doc_snazzy-aqua-kudu
      github.com/demichie/elicipy git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-cream-booby.sh
        container: qc.doc_gloppy-turquoise-macaque
      github.com/demichie/elicipy markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-olivine-setter.sh
        container: qc.doc_beady-scarlet-zonkey
  QC.Lic:
    repos:
      github.com/demichie/elicipy licensee:
        commands:
        - /usr/bin/env sh .sqa/script.messy-denim-bonobo.sh
        container: qc.lic_baggy-harlequin-uakari
  QC.Sec:
    repos:
      github.com/demichie/elicipy bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-taupe-gorilla.sh
        container: qc.sec_randy-black-camel
  QC.Sty:
    repos:
      github.com/demichie/elicipy flake8:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-harlequin-rottweiler.sh
        container: qc.sty_jumpy-chocolate-akita
  QC.Ver:
    repos:
      github.com/demichie/elicipy get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-russet-shrimp.sh
        container: qc.ver_chewy-burgundy-newfoundland
timeout: 5400
